# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        arguments:
            em: "@doctrine.orm.entity_manager"
            algorithm_service: "@algorithm_service"
        public: false
        tags:
            - { name: twig.extension }

    algorithm_service:
        class:        AppBundle\Service\AlgorithmService
        arguments:
            em: "@doctrine.orm.entity_manager"
